### ISSUE TITLE
Build fails on macOS 10.15 (Catalina): kIOMainPortDefault unavailable

### ISSUE THREAD

**Issue by OldCrow** [lavoiesl/osx-cpu-temp#53]
### Summary
`smc.c` fails to build on macOS 10.15 (Catalina):

```
smc.c:59:43: error: use of undeclared identifier 'kIOMainPortDefault'; did you mean 'kIOMasterPortDefault'?
    result = IOServiceGetMatchingServices(kIOMainPortDefault, matchingDictionary, &iterator);
                                          ^~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:103:19: note: 
      'kIOMasterPortDefault' declared here
const mach_port_t kIOMasterPortDefault;
```

### Root cause

`kIOMainPortDefault` was introduced in a later IOKit SDK than the one Catalina ships (its Command Line Tools SDK only has `kIOMasterPortDefault`). `kIOMasterPortDefault` is still present (deprecated but functional) on all currently-supported macOS versions, so using it instead is backward-compatible.

### Fix

```diff
--- a/smc.c
+++ b/smc.c
@@ -56,7 +56,7 @@ kern_return_t SMCOpen(void)
     io_object_t device;
 
     CFMutableDictionaryRef matchingDictionary = IOServiceMatching("AppleSMC");
-    result = IOServiceGetMatchingServices(kIOMainPortDefault, matchingDictionary, &iterator);
+    result = IOServiceGetMatchingServices(kIOMasterPortDefault, matchingDictionary, &iterator);
     if (result != kIOReturnSuccess) {
         printf("Error: IOServiceGetMatchingServices() = %08x\n", result);
         return 1;
```

Verified: builds and runs correctly on Catalina with this change (confirmed real CPU temperature readings).

### Environment
- macOS 10.15 (Catalina), Intel
- Xcode Command Line Tools (matching SDK)

Happy to open this as a PR instead if preferred.

Co-Authored-By: Warp <agent@warp.dev>
